// 
// Copyright (c) Microsoft and contributors.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

using AutoMapper;
using CNM = Microsoft.Azure.Commands.Network.Models;
using Microsoft.Azure.Management.Network.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;

namespace Microsoft.Azure.Commands.Network.Automation
{
    [Cmdlet("New", "AzureRmPacketCaptureFilterConfig", SupportsShouldProcess = true)]
    [OutputType(typeof(PacketCapture))]
    public class NewAzureRmPacketCaptureFilterConfigCommand : NetworkBaseCmdlet
    {
        [Parameter(
            Mandatory = false,
            Position = 0,
            ValueFromPipelineByPropertyName = true)]
        public string Protocol { get; set; }

        [Parameter(
            Mandatory = false,
            Position = 1,
            ValueFromPipelineByPropertyName = true)]
        public string LocalIPAddress { get; set; }

        [Parameter(
            Mandatory = false,
            Position = 2,
            ValueFromPipelineByPropertyName = true)]
        public string RemoteIPAddress { get; set; }

        [Parameter(
            Mandatory = false,
            Position = 3,
            ValueFromPipelineByPropertyName = true)]
        public string LocalPort { get; set; }

        [Parameter(
            Mandatory = false,
            ValueFromPipelineByPropertyName = true)]
        public string RemotePort { get; set; }

        [Parameter(
            Mandatory = false,
            HelpMessage = "Do not ask for confirmation if you want to overwrite a resource")]
        public SwitchParameter Force { get; set; }

        public override void Execute()
        {

            var vFilters = new Microsoft.Azure.Management.Network.Models.PacketCaptureFilter();

            vFilters.Protocol = this.Protocol;
            vFilters.LocalIPAddress = this.LocalIPAddress;
            vFilters.RemoteIPAddress = this.RemoteIPAddress;
            vFilters.LocalPort = this.LocalPort;
            vFilters.RemotePort = this.RemotePort;
            var vFiltersModel = Mapper.Map<CNM.PSPacketCaptureFilter>(vFilters);
            WriteObject(vFiltersModel);
        }
    }
}

