// 
// Copyright (c) Microsoft and contributors.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

using AutoMapper;
using Microsoft.Azure.Commands.ResourceManager.Common.Tags;
using Microsoft.Azure.Commands.Network.Models;
using Microsoft.Azure.Management.Network;
using Microsoft.Azure.Management.Network.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Management.Automation;
using CNM = Microsoft.Azure.Commands.Network.Models;

namespace Microsoft.Azure.Commands.Network.Automation
{
    [Cmdlet(VerbsCommon.Get, "AzureRmNetworkSecurityGroup", DefaultParameterSetName = "InvokeByDynamicParameters")]
    public partial class GetAzureRmNetworkSecurityGroup : NetworkBaseCmdlet
    {
        [Parameter(
            Mandatory = false,
            ValueFromPipelineByPropertyName = true)]
        [ValidateNotNullOrEmpty]
        public string ResourceGroupName { get; set; }
        [Parameter(
            Mandatory = false,
            ValueFromPipelineByPropertyName = true)]
        [ValidateNotNullOrEmpty]
        public string Name { get; set; }
        [Parameter(
            Mandatory = false,
            ValueFromPipelineByPropertyName = true)]
        [ValidateNotNullOrEmpty]
        public string Expand { get; set; }

        public override void Execute()
        {
            base.Execute();

            if (!string.IsNullOrEmpty(this.Name))
            {
                var vNetworkSecurityGroup = this.NetworkClient.NetworkManagementClient.NetworkSecurityGroups.Get(ResourceGroupName, Name, Expand);
                var vNetworkSecurityGroupModel = Mapper.Map<CNM.PSNetworkSecurityGroup>(vNetworkSecurityGroup);
                vNetworkSecurityGroupModel.ResourceGroupName = this.ResourceGroupName;
                vNetworkSecurityGroupModel.Tag = TagsConversionHelper.CreateTagHashtable(vNetworkSecurityGroup.Tags);
                WriteObject(vNetworkSecurityGroupModel);
            }
            else if (!string.IsNullOrEmpty(this.ResourceGroupName))
            {
                var vNetworkSecurityGroupList = this.NetworkClient.NetworkManagementClient.NetworkSecurityGroups.List(this.ResourceGroupName);
                foreach (var vNetworkSecurityGroup in vNetworkSecurityGroupList)
                {
                    var vNetworkSecurityGroupModel = Mapper.Map<CNM.PSNetworkSecurityGroup>(vNetworkSecurityGroup);
                    vNetworkSecurityGroupModel.ResourceGroupName = this.ResourceGroupName;
                    vNetworkSecurityGroupModel.Tag = TagsConversionHelper.CreateTagHashtable(vNetworkSecurityGroup.Tags);
                    WriteObject(vNetworkSecurityGroupModel);
                }
            }
            else
            {
                var vNetworkSecurityGroupList = this.NetworkClient.NetworkManagementClient.NetworkSecurityGroups.ListAll();
                foreach (var vNetworkSecurityGroup in vNetworkSecurityGroupList)
                {
                    var vNetworkSecurityGroupModel = Mapper.Map<CNM.PSNetworkSecurityGroup>(vNetworkSecurityGroup);
                    vNetworkSecurityGroupModel.ResourceGroupName = NetworkBaseCmdlet.GetResourceGroup(vNetworkSecurityGroup.Id);
                    vNetworkSecurityGroupModel.Tag = TagsConversionHelper.CreateTagHashtable(vNetworkSecurityGroup.Tags);
                    WriteObject(vNetworkSecurityGroupModel);
                }
            }
        }
    }
}
